name: Secret Security Test
on:
  push: # Use push to a branch for the easiest test
    branches: [ 'test-branch' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  leak-check:
    runs-on: ubuntu-latest
    steps:
      - name: Bypass Scrubber in Logs
        env:
          MY_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "$MY_SECRET" | sed 's/./&-/g'
